### ISSUE TITLE
TTL level serial

### ISSUE THREAD

**Issue by pmetzger** [ballaswag/k1-discovery#2]
Do you know what the pinout is for the TTL level serial port? Alternatively, do you know where to get an appropriate cable to use it?

**Comment by ballaswag** [comment]
If you’re referring to the pinouts for the load cell mcu then I have no idea at this time. I haven’t spend the time looking yet. For the debug serial, any 3.3V USB to TTL with tx, rx, gnd should work.

**Comment by pmetzger** [comment]
Like this one: https://www.amazon.com/Converter-Terminated-Galileo-BeagleBone-Minnowboard/dp/B06ZYPLFNB ?

I was contemplating setting up a Raspberry Pi Zero W as a "terminal server" to give me remote access to the serial console.

**Comment by ballaswag** [comment]
Something like this https://a.co/d/7eBGtqm. Just make sure you connect tx on adapter to rx on K1, and rx on adapter to tx on K1.
