### ISSUE TITLE
Wiki?

### ISSUE THREAD

**Issue by pmetzger** [ballaswag/k1-discovery#3]
Have you considered enabling the Wiki functionality so people can share things they've discovered here?

**Comment by ballaswag** [comment]
Need to understand how moderation will work. I can enable and give edit permission to users that want to contribute, but don’t want to be the only user moderating the contents on the wiki. Maybe the discussion feature for free form conversations might be a better form for now.

**Comment by pmetzger** [comment]
Maybe we can set up a shared repo for a bunch of people who are working on the thing to all share information, and we can let people do pull requests for changes.

**Comment by serhat-ozkara** [comment]
@ballaswag  Hello, it'd be better to combine efforts on https://discord.gg/E5uvwFnK

**Comment by pmetzger** [comment]
A bunch of us are on that Discord now, yes.

**Comment by hamyyy** [comment]
hey, can I get a link to the discord also? I have a few ideas in regard to the k1 max board, would love it if we could share some info

**Comment by ballaswag** [comment]
@hamyyy discord link is in above comment.

**Comment by hamyyy** [comment]
yes im aware, but its expired :p

**Comment by ballaswag** [comment]
try this https://discord.gg/BsMFcFTK
